

    services:
      db:
        image: postgres
        environment:
          - POSTGRES_DB=your_db_name
          - POSTGRES_USER=your_db_user
          - POSTGRES_PASSWORD=your_db_password
          - DATABASE_URL=${DATABASE_URL}
          - ENGINE=django.db.backends.postgresql
          - DJANGO_ENV=${DJANGO_ENV}
        ports:
          - "5432:5432"

      web:
        build: .
        command: python app/manage.py runserver 0.0.0.0:8000 --settings=nal.settings.test
        volumes:
          - .:/app
        ports:
          - "8000:8000"
        depends_on:
          - db
    